/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ARow: typeof import('ant-design-vue/es')['Row']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    CommonHeader: typeof import('./src/components/CommonHeader/index.vue')['default']
    CommonSider: typeof import('./src/components/CommonSider/index.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    OnlyIcon: typeof import('./src/components/icons/OnlyIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
    SvgIconDark: typeof import('./src/components/icons/SvgIconDark.vue')['default']
    SvgIconLight: typeof import('./src/components/icons/SvgIconLight.vue')['default']
  }
}
